config/routes.rb
SublimeLearning::Application.routes.draw do

	root to: 'lessons#landing'
  get "lessons/thats_all"

  resources :lessons, except: [:new] do
    member do
      get 'next'
    end
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new',            via: 'get'
  match '/login',   to: 'sessions#new',         via: 'get'
  match '/logout', to: 'sessions#destroy',     via: 'delete'

end

app/models/concerns/chapter.rb
class Chapter < ActiveRecord::Base
	has_many :lessons
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
	belongs_to :chapter
	validates :name, presence: true
	validates :number, presence: true
	validates :content, presence: true									 
	validates :answer, presence: true
	validates :number, presence: true,
	                        uniqueness: true
	validates :editable_code, presence: true
	validates :count, presence: true

	def next
		@lesson = Lesson.where(number: self.number + 1)
		@lesson.first
	end	

	def previous
		@lesson = Lesson.where(number: self.number - 1)	
		@lesson.first
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :name, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  validates :password_digest, presence: true

  before_save { self.email = email.downcase }
  before_create :create_remember_token
 
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  before_filter :author_user,  only: [:create, :edit, :destroy]

	def landing
		@lessons = Lesson.all
		@lesson = @lessons.first
	end

	def no_lesson
		@lessons = Lesson.all
		render('lessons/no_lesson.html.erb')
	end

	def index
		@lessons = Lesson.all
		@lesson = Lesson.new
	end

	def show
		@lessons = Lesson.all
		@lesson = Lesson.find(params[:id])
	end

	def create
		@lesson = Lesson.new(lessons_params)
		if @lesson.save
			redirect_to lessons_path
		else
			render 'new'
		end
	end

	def edit
		@lessons = Lesson.all
		@lesson = Lesson.find(params[:id])
		render('lessons/edit.html.erb')
	end

	def update
		@lesson = Lesson.find(params[:id])
		if @lesson.update(lessons_params)
			redirect_to lesson_path(@lesson)
		else
			render('lessons/edit.html.erb')
		end
	end
	

	def destroy
		@lesson = Lesson.find(params[:id])
    @lesson.destroy
    flash[:notice] = 'Lesson deleted.'
    redirect_to lessons_path
	end

  def next
    next_lesson = Lesson.find(params[:id]).next
    if next_lesson.present?
      redirect_to lesson_path(next_lesson)
    else
      redirect_to lessons_thats_all_path
    end
  end

private
	def lessons_params
    params.require(:lesson).permit(:name,
                                 :number,
                                 :chapter_id,
                                 :content,
                                 :editable_code,
                                 :answer,
                                 :editor_height,
                                 :line_number,
                                 :count)
	end
	def correct_user
        @user = User.find(params[:id])
        redirect_to(root_path) unless current_user?(@user)
    end

    def author_user
      redirect_to root_path unless current_user.author?
    
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  	@lessons = Lesson.all
  end

   def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
     sign_in user
     redirect_to lessons_path
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :signed_in_user, 
                only: [:show, :index, :edit, :update, :destroy]
  before_filter :correct_user, only: [:edit, :update, :destroy]
  before_filter :author_user,  only: :destroy
 

	def new
		@lessons = Lesson.all
		@users = User.all
		@user = User.new
	end

	def create
		@lessons = Lesson.all
		@user = User.new(user_params)
		if @user.save
			sign_in @user
			redirect_to lesson_path(@lessons.first)
		else
			redirect_to :back
		end
	end

	def index
		@users = User.all
		@lessons = Lesson.all
	end

	def show
		@user = User.find(params[:id])
		@lessons = Lesson.all
	end

	def edit
		@user = User.find(params[:id])
		@lessons = Lesson.all
	end
	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:notice] = "User updated."
			redirect_to user_path(@user)
		else
			render 'edit'
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to users_path
	end

	private
		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation, :author)
		end

		def signed_in_user
			redirect_to login_path, notice: "Please login." unless signed_in?
		end

		def correct_user
        @user = User.find(params[:id])
        redirect_to(root_path) unless current_user?(@user) || current_user.author?
    end

    def author_user
      redirect_to root_path unless current_user.author? 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "Sublime Learning"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/lesson_helper.rb
module LessonHelper
  def markdown(text)
    html = Redcarpet::Render::HTML.new(prettify: true)
    markdown = Redcarpet::Markdown.new(html, space_after_headers: true,
                                             fenced_code_blocks: true)
    markdown.render(text).html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.digest(remember_token))
		self.current_user = user
	end
	def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.digest(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end
	
	def current_user?(user)
		user == current_user
	end

	def author
		if @current_user.author == true
			true
		else
			false
		end
	end
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-error">
  	<h3>Please fix these errors:</h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div id="footer" class="bottom-bar">
	<div  class="row">
		<ul class="pull-right inline-list">
			<li><a href="#">Section Contents</a></li>

			<li><a href="/table-of-contents">Table of contents</a></li>
		</ul>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title)+" | Sublime Learning" : "Sublime Learning" %></title>

    <%= stylesheet_link_tag   "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %> 
    <%= javascript_include_tag  "application" %>

  </head>

  <body id="<%= controller.controller_name %>">

    <%= yield %>
    
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sublime Learning</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>



				<%= yield %>


</body>
</html>

app/views/lessons/_content.html.erb
<%= markdown @lesson.content %>

app/views/lessons/_editor.html.erb
<div class="row">
	<form id="cm-form">
		<textarea id="lesson-text">
<%= @lesson.editable_code %>
		</textarea>
  </form>
</div>

app/views/lessons/_form.html.erb
<%= form_for @lesson do |f| %>
  <%= render 'shared/error_messages', object: @lesson %>
  <div class="row">
    <div class="form-group small-6 column">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="form-group small-3 column">
      <%= f.label :number %>
      <%= f.text_field :number %>
    </div>
    <div class="form-group small-3 column end">
      <%= f.label :chapter_id %>
      <%= f.text_field :chapter_id %>
    </div>
  </div>
  <div class="row">
    <div class="form-group small-3 column">
      <%= f.label :count %>
      <%= f.text_field :count %>
    </div>
  </div>
  <div class="row">
    <div class="form-group small-12 column">
      <%= f.label :content %>
      <%= f.text_area :content, class: "content-field" %>
    </div>
  </div>
  <div class="row">
    <div class="form-group small-12 column">
      <%= f.label :editable_code %>
      <%= f.text_area :editable_code, class: "editable-code-field" %>
    </div>
  </div>
  <div class="row">
    <div class="form-group small-12 column">
      <%= f.label :answer %>
      <%= f.text_area :answer, class: "answer-field" %>
    </div>
  </div>
  <div class="row center">
    <%= f.submit "Save", class:  'button tiny'  %>
  </div>
 

<% end %>

app/views/lessons/_markdown.html.erb
	def change_this_method
	  puts &quot;This should be the second&quot;
	  puts &quot;This should be the first line&quot;
	end

app/views/lessons/_messages.html.erb
<button id="notice-correct" type="reset" class="">
	Good job! Wasn't that easy?
</button>
<button id="could-improve" type="reset" class="">
	Not bad, but you could have done that in less actions.
</button>
<button id="alert-wrong" type="reset" class="">
	Oops, not quite. Try using the short cut to fix the code.
</button>

app/views/lessons/admin.html.erb
<div class="row top-div">
  <h3>Lessons:</h3>
  <ul>
    <% @lessons.each do |lesson| %>
    <li><%= lesson.name %> <span class="small-links"><%= link_to "edit", edit_lesson_path(lesson), {method: 'get'} %> | <%= link_to "delete", "#" %></li></span>
    <% end %>
  </ul>
</div>
<div class="row">
  <h3>Create a new lesson</h3>
</div>
<div class="row">
  <form action="/lessons" method="post" id="new-lesson">
    <div class="row">
      <div class="form-group medium-13 columns">
        <label for="name">Lesson name</label><br>
        <input type="text" class="form-control fifty-percent" name="name" placeholder="Enter lesson name">
      </div>
    </div>

    <div class="row">
      <div class="form-group medium-2 columns">
        <label for="number">Lesson number</label><br>
        <input type="text" class="form-control ten-percent" name="number" placeholder="Enter number">
      </div>
    </div>

    <div class="row">
      <div class="form-group medium-2 columns">
        <label for="chapter_id">Chapter id</label><br>
        <input type="text" class="form-control ten-percent" name="chapter_id" placeholder="Enter number">
      </div>
    </div>

    <div class="row">
      <div class="form-group medium-12 columns">
        <label for="content">Lesson Content</label><br>
        <textarea name="content" class="form-control" rows="3" placeholder="Compose..."></textarea>
      </div>
    </div>
   
    <div class="row">
      <button type="submit" class="btn btn-default">Submit</button>
      <button href="/lessons/admin/edit" class="btn btn-default pull-right">Edit a lesson</button>
    </div>

  </form>
</div>

app/views/lessons/edit.html.erb
<%= content_for(:title, 'Edit lesson') %>
<%= render 'shared/navbar' %>
		<div class="light-blue">
			<div class="row top-div">
			  <h3>Edit lesson:</h3>
			</div>

			<div class='row bottom-space'>
			  <%= render 'layouts/errors', { object: @lesson } %>

			  <%= render 'form' %>
			</div>
		</div>
		<!-- closing divs for offcanvas -->
	</div>
</div>

app/views/lessons/edit_lesson.html.erb
<h1>Choose a lesson to edit</h1>
<ul class="table_of_contents">
	<% @lessons.each do |lesson| %>
		<li><a href="/lessons/<%= lesson.id %>/edit"><%= lesson.number %> <%= lesson.name %></a></li>
	<% end %>
</ul>

app/views/lessons/index.html.erb
<% content_for(:title, "Lessons") %>

<%= render 'shared/navbar' %>
<section class="main-section">
		<div class="drk-bckgrnd">
			<div class="row top-div">
			  <h3>Lessons:</h3>
			  <ul>
			  	<% @lessons.sort_by! { |lesson| lesson.number } %>
			    <% @lessons.each do |lesson| %>
			    <li>Lesson <%= lesson.number %>: <%= lesson.name %> <br>
			    	 <% if !current_user.nil? && current_user.author == true %>
			    	<span class="small-links"><%= link_to "edit", edit_lesson_path(lesson), { method: 'get' } %> | <%= link_to "delete", lesson_path(lesson), { confirm: 'You sure?', method: 'delete' } %></li></span>
			    	<% end %>
			    <% end %>
			    </ul>
			</div>

			<div class="row">
			  <% if !current_user.nil? && current_user.author == true %>
			  <h3>Create a new lesson</h3>
			</div>
			<div class="row bottom-space">
			  <%= render 'form' %>
			</div>
				<% end %>
		</div>
	</section>
		<!-- closing divs for offcanvas -->
	 </div>
</div>

app/views/lessons/landing.html.erb
<div class="main-page">
	<div class="row">
		<div class="small-12 columns main-title">
			<code class="orange">def</code>
			<code class="one-space red">be_a_keyboard_ninja</code><br>
			<code class="indent white">puts </code> <code class="string">"Learn Sublime Text Shortcuts!"</code><br>
			<code class="orange">end</code>
		</div>
	</div>
	<div class="row">
		<div class="small-4 small-centered columns start-button">
			<%= link_to "Get Started", @lesson, class: "button center" %>
		</div>
	</div>
</div>
<div class="more-info">
	<div class="row">
		<div class="small-12 small-centered columns">
			<p>This is a resource to help you gain fluency with <a href="http://www.sublimetext.com/">Sublime Text</a> keyboard shortcuts and bring more joy to your coding experience.</p>
			<p class="tight-bottom">It is a work in progress and does yet not include all the wonderful shortcuts built into Sublime. This project is open source so if you would like to contribute feel free to fork it on <a href="https://github.com/Bw00d/sublime_learning">Github</a>.</p>
		</div>
	</div>
	<div class="row">
		<div class="small-1 small-centered columns">
			<p><a href="https://github.com/Bw00d"><%= image_tag "octocat-pinkface.png" %></a></p>
		</div>
	</div>
</div>

app/views/lessons/new.html.erb
<%= render 'form' %>

app/views/lessons/show.html.erb
<%= content_for(:title, @lesson.name) %>

<%= render 'shared/navbar' %>

    <section class="main-section">
    	<%= hidden_field_tag "count", @lesson.count, id: 'best-count' %>
			<div class="large-9 large-centered columns lesson bottom-space">
				<h1 id="lesson-name" class="center"><%= @lesson.name %></h1>
				<div class="content">
					<%= markdown @lesson.content %>
				</div>

				<p id="answer-block">
					<%= @lesson.answer %>
				</p>
				<p id="line-number">
					<%= @lesson.line_number %>
				</p>
				
					<div id="cm-editor">
						<%= render 'editor' %>
					</div>
		

			  <button id="submit-button" type="submit" class="">submit</button>
			  <button id="reset-button" type="submit" class="">reset</button>
				<%= link_to "skip", next_lesson_path(@lesson), id: "next", class: "button inactive" %>

			  <%= render "messages" %>
				<div class="small-1 small-centered columns">
					<p><a href="https://github.com/Bw00d"><%= image_tag "octocat-pinkface.png", id: "octocat-link", alt: "octocat-logo" %></a></p>
				</div>
			</div>
		</section>
  <!-- closing divs for offcanvas -->
			</div>
  </div>

<script>
$(document).ready(function() {
  var editor = CodeMirror.fromTextArea(document.getElementById("lesson-text"), {
    lineNumbers: true,
    mode: "ruby",
    matchBrackets: true,
    indentUnit: 2,
    theme : 'railscasts',
    keyMap: "sublime",
    tabSize: 2,
    activeLine: true,
    showTrailingSpace: false
  });
  // for counting strokes
  var count = 0;
  $('textarea').on('keyup',function(){
     count++;
      
    });

	$('#submit-button').click( function() {
	  var bestCount = $('#best-count').val();
		$('#reset-button').show();
		// editor = $("#lesson-text");
		var input = editor.getValue().trim();
		var output = input.replace(/[^\S\r\n]+$/gm, "")
		var answer = $('#answer-block').html().trim();
		var last_answer = answer.replace(/[^\S\r\n]+$/gm, "")
		var result = last_answer.localeCompare(output);
		if (result == 0 ) {
			$('#submit-button').hide();
			if (count < parseInt(bestCount) ){
				// $('#notice-correct').append(" " + count + "clicks"); //counted strokes
				$('#notice-correct').show();
			} else {
				$('#could-improve').show()
			}
			$('#next').removeClass('inactive');
			$('#next').text('next lesson');
			$('#next').addClass('active');
		} else {
			$('#alert-wrong').show();
		}
	});
	$('#reset-button').click( function(event) {
		event.preventDefault();
		$('#reset-button').hide();
		$('#submit-button').show();
		location.reload();
	});
	
});
</script>

app/views/lessons/table_of_contents.html.erb
<!-- <h1>Table of contents</h1>
<ul class="table_of_contents">
	<% @lessons.each do |lesson| %>
		<li><a href="/lessons/<%= lesson.id %>"><%= lesson.name %></a></li>
	<% end %>
</ul> -->

<nav class="tab-bar">
  <section class="left-small">
    <a class="left-off-canvas-toggle menu-icon" ><span></span></a>
  </section>
  <section class="right-small">
    <a class="right-off-canvas-toggle menu-icon" ><span></span></a>
  </section>
</nav>

app/views/lessons/thats_all.html.erb
<%= content_for(:title, "That's all for now") %>

<%= render 'shared/navbar' %>

		<div class="more-info">
			<div class="row">
				<div class="no-lesson">
					<div class="small-12 small-centered columns">
						<h3><strong>That's all for now!</strong></h3>
						<p>I hope you enjoyed this resource.</p>
						<p>I will add more lessons when I get some free time.</p>
			
						<p class="tight-bottom">If you would like to help out with either making new lessons or improving the code checkout it out on <a href="https://github.com/Bw00d/sublime_learning">Github</a>.</p>
					</div>
				</div>
			</div>

		
			<div class="row">
				<div class="small-1 small-centered columns">
					<p><a href="https://github.com/Bw00d"><%= image_tag "octocat-pinkface.png" %></a></p>
				</div>
			</div>
		</div>
	<!-- closing divs for offcanvas -->
	 </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="off-canvas-wrap" data-offcanvas>
  <div class="inner-wrap" data-no-turbolink>
    <nav class="tab-bar">
      <section class="left-small">
        <a id="left-menu" class="left-off-canvas-toggle menu-icon" href="#"><span></span></a>
      </section>

      <section class="middle tab-bar-section">
        <h1 class="title"><%= link_to "Learn Sublime", root_path %></h1>
      </section>

      <section class="right-small">
        <a id="right-menu" class="right-off-canvas-toggle menu-icon" href="#"><span></span></a>
      </section>
    </nav>

    <aside class="left-off-canvas-menu">
      <ul class="off-canvas-list">
        <li><label>Lessons</label></li>
        <li><%= link_to "Lessons", lessons_path %></li>
        <% if @lessons %>
        <% @lessons.sort_by! { |lesson| lesson.number } %>
          <% @lessons.each do |lesson| %>
            <li><a href="/lessons/<%= lesson.id %>"><%= lesson.name %></a></li>
          <% end %>
        <% end %>
      </ul>
    </aside>

     <aside class="right-off-canvas-menu">
      <ul class="off-canvas-list">
        <li><label>User</label></li>
        <% if signed_in? %>
        <% if current_user.author %>

        <li><%= link_to "All users", users_path %></li>
        <% end %>
        <li><%= link_to "Logout", logout_path, method: "delete" %></li>
        <li><%= link_to "Help", "#" %></li>
        <% else %>
        <li><%= link_to "Login", login_path %></li>
        <li><%= link_to "Sign up", new_user_path %></li>
        <% end %>
      </ul>
      <ul id="user-info">
        <% if signed_in? %>
        <li>Hello, <%= current_user.name %></li>
        <% end %>
      </ul>
    </aside>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<%= render 'shared/error_messages', object: @user %>
  <div class="row">
		<div class="form-group small-6 column">
	    <%= f.label :name %>
	    <%= f.text_field :name %>
	  </div>
		<div class="form-group small-6 column">
		  <%= f.label :email %>
		  <%= f.text_field :email %>
	  </div>
  </div>
  <div class="row">
	  <div class="form-group small-6 column">
		  <%= f.label :password %>
		  <%= f.text_field :password %>
	  </div>
	  <div class="form-group small-6 column">
		  <%= f.label "Confirmation" %>
		  <%= f.text_field :password_confirmation %>
	  </div>
	</div>
  <div class="row center">
    <%= f.submit "Submit", class: 'button tiny'  %>
  </div>
<% end %>

app/views/users/_users.html.erb
<li>
	<%= link_to user.name, user_path(user.id) %>
	<% if user.author %>
						<span class="author">author</span></li>
						<% end %>
	<% if current_user.author || current_user?(user) %>
	<%= link_to "edit", edit_user_path(user) %> | 
	<%= link_to "delete", user, confirm: "You sure?", method: "delete" %></p>
	<% end %>
</li>	

app/views/users/edit.html.erb
<% content_for(:title, "Edit") %>

<%= render 'shared/navbar' %>
<section class="main-section">
		<div class="drk-bckgrnd">
			<div class="row top-div half-page">
				<h3>Update</h3>
				<%= render 'users/form' %>
			</div>
		</div>

		<div class="icon-container">
			<div class="small-1 small-centered columns">
				<p><a href="https://github.com/Bw00d"><%= image_tag "octocat-pinkface.png", id: "octocat-link", alt: "octocat-logo" %></a></p>
			</div>
		</div>
	</div>
</section>
		<!-- closing divs for offcanvas -->
	 </div>
</div>

app/views/users/index.html.erb
<% content_for(:title, "Users") %>

<%= render 'shared/navbar' %>
<section class="main-section">
		<div class="drk-bckgrnd">
			<div class="row top-div half-page">
			<h1>All Users</h1>
				<ul>

					<% @users.each do |user|  %>
					<li>
						<%= link_to user.name, user %>  
						<% if user.author %>
											<span class="author"> author</span></li>  
											<% end %>
						<% if current_user.author || current_user?(user) %>
						<p class="user-change"><%= link_to "edit", edit_user_path(user) %> | 
						<%= link_to "delete", user, confirm: "You sure?", method: "delete" %></p>
						<% end %>
					</li>	
					<% end %>
				</ul>
			</div>
		</div>

				<div class="icon-container">
					<div class="small-1 small-centered columns">
						<p><a href="https://github.com/Bw00d"><%= image_tag "octocat-pinkface.png", id: "octocat-link", alt: "octocat-logo" %></a></p>
					</div>
				</div>
	</div>
</section>
		<!-- closing divs for offcanvas -->
	 </div>
</div>

app/views/users/new.html.erb
<% content_for(:title, "Sign up") %>

<%= render 'shared/navbar' %>
<section class="main-section">
		<div class="drk-bckgrnd">
			<div class="row top-div half-page">
				<h3>Make an account</h3>
				<%= render 'users/form' %>
			</div>
		</div>
		<div class="bottom-div">
			<h3>All Users</h3>
				<ul>
					<% @users.each do |user|  %>
					<li><strong><%= link_to user.name , user_path(user.id) %></strong>  
						<% if user.author %>
						<span class="author">author</span></li>
						<% end %>
					<% end %>
				</ul>
		</div>

				<div class="icon-container">
					<div class="small-1 small-centered columns">
						<p><a href="https://github.com/Bw00d"><%= image_tag "octocat-pinkface.png", id: "octocat-link", alt: "octocat-logo" %></a></p>
					</div>
				</div>
	</div>
</section>
		<!-- closing divs for offcanvas -->
	 </div>
</div>

app/views/users/show.html.erb
<% content_for(:title, @user.name) %>

<%= render 'shared/navbar' %>

<section class="main-section">
	<div class="drk-bckgrnd">
		<div class="row top-div half-page">
			<h3><%= @user.name %></h3>
			<h5><%= @user.email %></h5>
			<p><%= link_to "Edit", edit_user_path %> | <%= link_to "Delete", user_path(@user),
												 confirm: "You sure?",
												 method: "delete" %></p>
		</div>

	</div>
		<div class="icon-container">
			<div class="small-1 small-centered columns">
				<p><a href="https://github.com/Bw00d"><%= image_tag "octocat-pinkface.png", id: "octocat-link", alt: "octocat-logo" %></a></p>
			</div>
		</div>
</section>
		<!-- closing divs for offcanvas -->
	 </div>
</div>